travis:
  secure:
    BINSTAR_TOKEN: i69Po1fUWBkNrhRPDusr1FSeVQZwDKkzXHXzAIgr5o01cWgN+8ma18uMWRUJ6vIxAUeAJrhfJli+f8M5CxQ7rNqVphUEFDlyZ/T25fG8jOzNFyVx31KoWWVWQ2lSuSnV1k7Of2NpCOewmyAJ47+5ra16vfPsdhuBcsuAfpeuntDdt/qdO5jh1XpbIIEuK2CmSqtdZf4qqesk37oAzG0hDbp/q9elW1L0hZajkxREnLWIBa5nA8PXU0S1Ae19q0kieInZEAG7mf124pit7E31gx4FepMX6e6utnhm6sNXg9pNiLI5WqCTWJehrk+5EUGD6CCzERNQgYSefZ+DGpkOtu4hJTScTMElcbndveXV36965cMHFjV0jkZxw2enF/R53jkUEemuBoLGkaM1MK56m4oG9a9a0uAhF3PvNehVpe9YhMlX7AXoqcFs74/ab0OOBOomea/Uy3UqX2TuxYFy8ooi+aL7Oe+nhCGmo4SFh+TQT794NElJzcdAVwgGrJ/BGwBinezMeQzKEWBev1zgifQH1j2ih9JcmnsPgvREDO42xAZCjeIXjrlNB86RLQw4IzAQmDO779YsKJiRulpycXP3/Of26ikPb7vzCD1lFTfCpsmFwkN+csjNGiQS8p58RkyzKt/kry0z0Mld8g6zWLiGtJU7N5pS/evSNcaNdF4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
